"""sprint_2 db 4.3

Revision ID: 12831f536b97
Revises: 978550e03011
Create Date: 2020-01-19 18:12:58.491813

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12831f536b97'
down_revision = '978550e03011'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ProfileItems',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['profile'], ['Profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ProfilesAnswers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_item', sa.Integer(), nullable=True),
    sa.Column('response', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['profile_item'], ['ProfileItems.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ProfilesAnswers')
    op.drop_table('ProfileItems')
    op.drop_table('Profiles')
    # ### end Alembic commands ###
