"""new

Revision ID: 29a95f39cb12
Revises: 245033564e25
Create Date: 2019-11-13 23:48:50.784904

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29a95f39cb12'
down_revision = '245033564e25'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Users', sa.Column('email1', sa.String(length=100), nullable=True))
    op.create_index(op.f('ix_Users_email1'), 'Users', ['email1'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Users_email1'), table_name='Users')
    op.drop_column('Users', 'email1')
    # ### end Alembic commands ###
