"""sprint 2 db_5_5

Revision ID: 3772c81b9cce
Revises: f07308eff3ea
Create Date: 2020-02-10 21:48:47.468864

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3772c81b9cce'
down_revision = 'f07308eff3ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Histories', sa.Column('doctor_researcher', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_Histories_doctor_researcher'), 'Histories', ['doctor_researcher'], unique=False)
    op.create_foreign_key(None, 'Histories', 'Doctors', ['doctor_researcher'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Histories', type_='foreignkey')
    op.drop_index(op.f('ix_Histories_doctor_researcher'), table_name='Histories')
    op.drop_column('Histories', 'doctor_researcher')
    # ### end Alembic commands ###
