"""sprint 2 v1

Revision ID: 75bc1abe99e0
Revises: 8f0c9c8f741a
Create Date: 2020-01-03 16:30:25.898562

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75bc1abe99e0'
down_revision = '8f0c9c8f741a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Checkups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=100), nullable=True),
    sa.Column('is_mandatory', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Checkups_is_mandatory'), 'Checkups', ['is_mandatory'], unique=False)
    op.create_table('Events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=100), nullable=True),
    sa.Column('type', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Events_type'), 'Events', ['type'], unique=False)
    op.create_table('IndicatorsGroups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('OperationSteps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=100), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order')
    )
    op.create_table('OperationTypes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Сomplications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=100), nullable=True),
    sa.Column('type', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Сomplications_type'), 'Сomplications', ['type'], unique=False)
    op.create_table('Indicators',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=100), nullable=True),
    sa.Column('group', sa.Integer(), nullable=True),
    sa.Column('unit', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['group'], ['IndicatorsGroups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('IndicatorsDefs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('indicator', sa.Integer(), nullable=True),
    sa.Column('text_value', sa.String(length=100), nullable=True),
    sa.Column('num_value', sa.Numeric(), nullable=True),
    sa.ForeignKeyConstraint(['indicator'], ['Indicators.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_IndicatorsDefs_indicator'), 'IndicatorsDefs', ['indicator'], unique=False)
    op.create_table('IndicatorsNorms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('indicator', sa.Integer(), nullable=True),
    sa.Column('nvalue_from', sa.Numeric(), nullable=True),
    sa.Column('nvalue_to', sa.Numeric(), nullable=True),
    sa.ForeignKeyConstraint(['indicator'], ['Indicators.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_IndicatorsNorms_indicator'), 'IndicatorsNorms', ['indicator'], unique=False)
    op.create_index(op.f('ix_DiagnosesItems_type'), 'DiagnosesItems', ['type'], unique=False)
    op.add_column('Patients', sa.Column('birthdate', sa.Date(), nullable=True))
    op.add_column('Patients', sa.Column('sex', sa.String(length=1), nullable=True))
    op.add_column('Patients', sa.Column('snils_hash', sa.String(length=128), nullable=True))
    op.create_index(op.f('ix_Patients_sex'), 'Patients', ['sex'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Patients_sex'), table_name='Patients')
    op.drop_column('Patients', 'snils_hash')
    op.drop_column('Patients', 'sex')
    op.drop_column('Patients', 'birthdate')
    op.drop_index(op.f('ix_DiagnosesItems_type'), table_name='DiagnosesItems')
    op.drop_index(op.f('ix_IndicatorsNorms_indicator'), table_name='IndicatorsNorms')
    op.drop_table('IndicatorsNorms')
    op.drop_index(op.f('ix_IndicatorsDefs_indicator'), table_name='IndicatorsDefs')
    op.drop_table('IndicatorsDefs')
    op.drop_table('Indicators')
    op.drop_index(op.f('ix_Сomplications_type'), table_name='Сomplications')
    op.drop_table('Сomplications')
    op.drop_table('OperationTypes')
    op.drop_table('OperationSteps')
    op.drop_table('IndicatorsGroups')
    op.drop_index(op.f('ix_Events_type'), table_name='Events')
    op.drop_table('Events')
    op.drop_index(op.f('ix_Checkups_is_mandatory'), table_name='Checkups')
    op.drop_table('Checkups')
    # ### end Alembic commands ###
