"""sprint 2 db 4.4

Revision ID: 7ba474b8365a
Revises: 12831f536b97
Create Date: 2020-01-19 20:39:07.268621

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ba474b8365a'
down_revision = '12831f536b97'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Indicators', sa.Column('is_calculated', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###
    op.create_table('Complications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=100), nullable=True),
    sa.Column('type', sa.String(length=100), nullable=True)
    )
    op.create_index(op.f('ix_Complications_type'), 'Complications', ['type'], unique=False)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Indicators', 'is_calculated')
    # ### end Alembic commands ###
