"""sprint 2 db 4.1

Revision ID: 7d659f8770ff
Revises: 75bc1abe99e0
Create Date: 2020-01-10 11:28:03.540539

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d659f8770ff'
down_revision = '75bc1abe99e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ResearchGroups_description_key', 'ResearchGroups', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('ResearchGroups_description_key', 'ResearchGroups', ['description'])
    # ### end Alembic commands ###
