"""sprint 2 db 4.9

Revision ID: 8b794b9ebb73
Revises: 5d7c8ee54269
Create Date: 2020-01-26 20:02:46.993558

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b794b9ebb73'
down_revision = '5d7c8ee54269'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Histories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clinic', sa.Integer(), nullable=True),
    sa.Column('hist_number', sa.String(length=100), nullable=True),
    sa.Column('time_created', sa.DateTime(), nullable=True),
    sa.Column('patient', sa.Integer(), nullable=True),
    sa.Column('research_group', sa.Integer(), nullable=True),
    sa.Column('time_research_in', sa.DateTime(), nullable=True),
    sa.Column('time_research_out', sa.DateTime(), nullable=True),
    sa.Column('reason', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['clinic'], ['Clinics.id'], ),
    sa.ForeignKeyConstraint(['patient'], ['Patients.id'], ),
    sa.ForeignKeyConstraint(['reason'], ['Reasons.id'], ),
    sa.ForeignKeyConstraint(['research_group'], ['ResearchGroups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ProfilesAnswers')
    # ### end Alembic commands ###
