"""sprint 2 bd 4.2

Revision ID: 978550e03011
Revises: 7d659f8770ff
Create Date: 2020-01-13 11:46:45.965053

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '978550e03011'
down_revision = '7d659f8770ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Сomplications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=100), nullable=True),
    sa.Column('type', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Сomplications_type'), 'Сomplications', ['type'], unique=False)
    op.create_index(op.f('ix_Patients_sex'), 'Patients', ['sex'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Patients_sex'), table_name='Patients')
    op.drop_index(op.f('ix_Сomplications_type'), table_name='Сomplications')
    op.drop_table('Сomplications')
    # ### end Alembic commands ###
