"""sprint 2 db 5.3

Revision ID: a1ccd1c22e46
Revises: 891d82fa0857
Create Date: 2020-01-29 18:41:10.870952

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1ccd1c22e46'
down_revision = '891d82fa0857'
branch_labels = None
depends_on = None


def upgrade():
    pass
    # ### commands auto generated by Alembic - please adjust! ###
    #op.add_column('Histories', sa.Column('date_research_in', sa.Date(), nullable=True))
    #op.add_column('Histories', sa.Column('date_research_out', sa.Date(), nullable=True))
    #op.drop_column('Histories', 'time_research_in')
    #op.drop_column('Histories', 'time_research_out')
    # ### end Alembic commands ###


def downgrade():
    pass
    # ### commands auto generated by Alembic - please adjust! ###
    #op.add_column('Histories', sa.Column('time_research_out', sa.DATETIME(), nullable=True))
    #op.add_column('Histories', sa.Column('time_research_in', sa.DATETIME(), nullable=True))
    #op.drop_column('Histories', 'date_research_out')
    #op.drop_column('Histories', 'date_research_in')
    # ### end Alembic commands ###
