"""sprint 2 db 4.6

Revision ID: acddb38691ac
Revises: 7ba474b8365a
Create Date: 2020-01-20 22:27:11.123187

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'acddb38691ac'
down_revision = '7ba474b8365a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Сomplications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=100), nullable=True),
    sa.Column('type', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Сomplications_type'), 'Сomplications', ['type'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Сomplications_type'), table_name='Сomplications')
    op.drop_table('Сomplications')
    # ### end Alembic commands ###
