"""sprint 2 db 4.7

Revision ID: afc6454db7c7
Revises: 303133d79ede
Create Date: 2020-01-26 19:09:28.232964

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'afc6454db7c7'
down_revision = '303133d79ede'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ProfileItems',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=100), nullable=True),
    sa.Column('item_group', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['profile'], ['Profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ProfilesAnswers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile', sa.Integer(), nullable=True),
    sa.Column('profile_item', sa.Integer(), nullable=True),
    sa.Column('response', sa.String(length=100), nullable=True),
    sa.Column('response_value', sa.Numeric(), nullable=True),
    sa.ForeignKeyConstraint(['profile_item'], ['ProfileItems.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ProfilesAnswers', type_='foreignkey')
    op.drop_column('ProfilesAnswers', 'response_value')
    op.drop_column('ProfilesAnswers', 'profile')
    op.drop_column('ProfileItems', 'item_group')
    op.create_table('Checkups',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('description', sa.VARCHAR(length=100), nullable=True),
    sa.Column('is_mandatory', sa.BOOLEAN(), nullable=True),
    sa.CheckConstraint('is_mandatory IN (0, 1)'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_Checkups_is_mandatory', 'Checkups', ['is_mandatory'], unique=False)
    # ### end Alembic commands ###
