"""sprint 2 db 5

Revision ID: ba4b236c13e9
Revises: 8b794b9ebb73
Create Date: 2020-01-26 20:12:04.454753

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba4b236c13e9'
down_revision = '8b794b9ebb73'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Histories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clinic', sa.Integer(), nullable=True),
    sa.Column('hist_number', sa.String(length=100), nullable=True),
    sa.Column('time_created', sa.DateTime(), nullable=True),
    sa.Column('date_in', sa.Date(), nullable=True),
    sa.Column('patient', sa.Integer(), nullable=True),
    sa.Column('research_group', sa.Integer(), nullable=True),
    sa.Column('time_research_in', sa.DateTime(), nullable=True),
    sa.Column('time_research_out', sa.DateTime(), nullable=True),
    sa.Column('reason', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['clinic'], ['Clinics.id'], ),
    sa.ForeignKeyConstraint(['patient'], ['Patients.id'], ),
    sa.ForeignKeyConstraint(['reason'], ['Reasons.id'], ),
    sa.ForeignKeyConstraint(['research_group'], ['ResearchGroups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Diagnoses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clinic', sa.Integer(), nullable=True),
    sa.Column('history', sa.Integer(), nullable=True),
    sa.Column('patient', sa.Integer(), nullable=True),
    sa.Column('diagnose', sa.Integer(), nullable=True),
    sa.Column('side_damage', sa.String(length=100), nullable=True),
    sa.Column('date_created', sa.Date(), nullable=True),
    sa.Column('prothes', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['clinic'], ['Clinics.id'], ),
    sa.ForeignKeyConstraint(['diagnose'], ['Diagnoses.id'], ),
    sa.ForeignKeyConstraint(['history'], ['Histories.id'], ),
    sa.ForeignKeyConstraint(['patient'], ['Patients.id'], ),
    sa.ForeignKeyConstraint(['prothes'], ['Prosthesis.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Diagnoses')
    op.drop_table('Histories')
    # ### end Alembic commands ###
