"""sprint 2 db 5.4

Revision ID: f07308eff3ea
Revises: a1ccd1c22e46
Create Date: 2020-01-29 18:49:12.368174

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f07308eff3ea'
down_revision = 'a1ccd1c22e46'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Histories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clinic', sa.Integer(), nullable=True),
    sa.Column('hist_number', sa.String(length=100), nullable=True),
    sa.Column('time_created', sa.DateTime(), nullable=True),
    sa.Column('date_in', sa.Date(), nullable=True),
    sa.Column('patient', sa.Integer(), nullable=True),
    sa.Column('research_group', sa.Integer(), nullable=True),
    sa.Column('date_research_in', sa.Date(), nullable=True),
    sa.Column('date_research_out', sa.Date(), nullable=True),
    sa.Column('reason', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['clinic'], ['Clinics.id'], ),
    sa.ForeignKeyConstraint(['patient'], ['Patients.id'], ),
    sa.ForeignKeyConstraint(['reason'], ['Reasons.id'], ),
    sa.ForeignKeyConstraint(['research_group'], ['ResearchGroups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Histories_clinic'), 'Histories', ['clinic'], unique=False)
    op.create_index(op.f('ix_Histories_research_group'), 'Histories', ['research_group'], unique=False)
    op.create_table('Diagnoses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clinic', sa.Integer(), nullable=True),
    sa.Column('history', sa.Integer(), nullable=True),
    sa.Column('patient', sa.Integer(), nullable=True),
    sa.Column('diagnose', sa.Integer(), nullable=True),
    sa.Column('side_damage', sa.String(length=100), nullable=True),
    sa.Column('date_created', sa.Date(), nullable=True),
    sa.Column('prothes', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['clinic'], ['Clinics.id'], ),
    sa.ForeignKeyConstraint(['diagnose'], ['Diagnoses.id'], ),
    sa.ForeignKeyConstraint(['history'], ['Histories.id'], ),
    sa.ForeignKeyConstraint(['patient'], ['Patients.id'], ),
    sa.ForeignKeyConstraint(['prothes'], ['Prosthesis.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Diagnoses_clinic'), 'Diagnoses', ['clinic'], unique=False)
    op.create_index(op.f('ix_Diagnoses_history'), 'Diagnoses', ['history'], unique=False)
    op.create_table('HistoryEvents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clinic', sa.Integer(), nullable=True),
    sa.Column('history', sa.Integer(), nullable=True),
    sa.Column('patient', sa.Integer(), nullable=True),
    sa.Column('event', sa.Integer(), nullable=True),
    sa.Column('date_begin', sa.Date(), nullable=True),
    sa.Column('date_end', sa.Date(), nullable=True),
    sa.Column('doctor', sa.Integer(), nullable=True),
    sa.Column('doctor_researcher', sa.Integer(), nullable=True),
    sa.Column('doctor_chief', sa.Integer(), nullable=True),
    sa.Column('days1', sa.Integer(), nullable=True),
    sa.Column('days2', sa.Integer(), nullable=True),
    sa.Column('days3', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['clinic'], ['Clinics.id'], ),
    sa.ForeignKeyConstraint(['doctor'], ['Doctors.id'], ),
    sa.ForeignKeyConstraint(['doctor_chief'], ['Doctors.id'], ),
    sa.ForeignKeyConstraint(['doctor_researcher'], ['Doctors.id'], ),
    sa.ForeignKeyConstraint(['event'], ['Events.id'], ),
    sa.ForeignKeyConstraint(['history'], ['Histories.id'], ),
    sa.ForeignKeyConstraint(['patient'], ['Patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_HistoryEvents_doctor'), 'HistoryEvents', ['doctor'], unique=False)
    op.create_index(op.f('ix_HistoryEvents_doctor_chief'), 'HistoryEvents', ['doctor_chief'], unique=False)
    op.create_index(op.f('ix_HistoryEvents_doctor_researcher'), 'HistoryEvents', ['doctor_researcher'], unique=False)
    op.create_index(op.f('ix_HistoryEvents_event'), 'HistoryEvents', ['event'], unique=False)
    op.create_table('Operations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clinic', sa.Integer(), nullable=True),
    sa.Column('history', sa.Integer(), nullable=True),
    sa.Column('patient', sa.Integer(), nullable=True),
    sa.Column('doctor_surgeon', sa.Integer(), nullable=True),
    sa.Column('doctor_assistant', sa.Integer(), nullable=True),
    sa.Column('operation_order', sa.Integer(), nullable=True),
    sa.Column('time_begin', sa.DateTime(), nullable=True),
    sa.Column('time_end', sa.DateTime(), nullable=True),
    sa.Column('duration_min', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['clinic'], ['Clinics.id'], ),
    sa.ForeignKeyConstraint(['doctor_assistant'], ['Doctors.id'], ),
    sa.ForeignKeyConstraint(['doctor_surgeon'], ['Doctors.id'], ),
    sa.ForeignKeyConstraint(['history'], ['Histories.id'], ),
    sa.ForeignKeyConstraint(['patient'], ['Patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Operations_clinic'), 'Operations', ['clinic'], unique=False)
    op.create_table('IndicatorValues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clinic', sa.Integer(), nullable=True),
    sa.Column('history', sa.Integer(), nullable=True),
    sa.Column('patient', sa.Integer(), nullable=True),
    sa.Column('history_event', sa.Integer(), nullable=True),
    sa.Column('indicator', sa.Integer(), nullable=True),
    sa.Column('slice', sa.String(length=100), nullable=True),
    sa.Column('time_created', sa.DateTime(), nullable=True),
    sa.Column('text_value', sa.String(length=100), nullable=True),
    sa.Column('num_value', sa.Numeric(), nullable=True),
    sa.Column('num_deviation', sa.Numeric(), nullable=True),
    sa.Column('comment', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['clinic'], ['Clinics.id'], ),
    sa.ForeignKeyConstraint(['history'], ['Histories.id'], ),
    sa.ForeignKeyConstraint(['history_event'], ['HistoryEvents.id'], ),
    sa.ForeignKeyConstraint(['indicator'], ['Indicators.id'], ),
    sa.ForeignKeyConstraint(['patient'], ['Patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_IndicatorValues_clinic'), 'IndicatorValues', ['clinic'], unique=False)
    op.create_index(op.f('ix_IndicatorValues_history'), 'IndicatorValues', ['history'], unique=False)
    op.create_table('OperationComp',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clinic', sa.Integer(), nullable=True),
    sa.Column('history', sa.Integer(), nullable=True),
    sa.Column('patient', sa.Integer(), nullable=True),
    sa.Column('operation', sa.Integer(), nullable=True),
    sa.Column('complication', sa.Integer(), nullable=True),
    sa.Column('date_begin', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['clinic'], ['Clinics.id'], ),
    sa.ForeignKeyConstraint(['complication'], ['Complications.id'], ),
    sa.ForeignKeyConstraint(['history'], ['Histories.id'], ),
    sa.ForeignKeyConstraint(['operation'], ['Operations.id'], ),
    sa.ForeignKeyConstraint(['patient'], ['Patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_OperationComp_clinic'), 'OperationComp', ['clinic'], unique=False)
    op.create_table('OperationLog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clinic', sa.Integer(), nullable=True),
    sa.Column('history', sa.Integer(), nullable=True),
    sa.Column('patient', sa.Integer(), nullable=True),
    sa.Column('operation', sa.Integer(), nullable=True),
    sa.Column('operation_step', sa.Integer(), nullable=True),
    sa.Column('time_begin', sa.DateTime(), nullable=True),
    sa.Column('time_end', sa.DateTime(), nullable=True),
    sa.Column('duration_min', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['clinic'], ['Clinics.id'], ),
    sa.ForeignKeyConstraint(['history'], ['Histories.id'], ),
    sa.ForeignKeyConstraint(['operation'], ['Operations.id'], ),
    sa.ForeignKeyConstraint(['operation_step'], ['OperationSteps.id'], ),
    sa.ForeignKeyConstraint(['patient'], ['Patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_OperationLog_clinic'), 'OperationLog', ['clinic'], unique=False)
    op.create_table('ProfileResponses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clinic', sa.Integer(), nullable=True),
    sa.Column('history', sa.Integer(), nullable=True),
    sa.Column('patient', sa.Integer(), nullable=True),
    sa.Column('history_event', sa.Integer(), nullable=True),
    sa.Column('profile', sa.Integer(), nullable=True),
    sa.Column('profile_item', sa.Integer(), nullable=True),
    sa.Column('response', sa.String(length=100), nullable=True),
    sa.Column('response_value', sa.Numeric(), nullable=True),
    sa.ForeignKeyConstraint(['clinic'], ['Clinics.id'], ),
    sa.ForeignKeyConstraint(['history'], ['Histories.id'], ),
    sa.ForeignKeyConstraint(['history_event'], ['HistoryEvents.id'], ),
    sa.ForeignKeyConstraint(['patient'], ['Patients.id'], ),
    sa.ForeignKeyConstraint(['profile'], ['Profiles.id'], ),
    sa.ForeignKeyConstraint(['profile_item'], ['ProfileItems.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ProfileResponses_clinic'), 'ProfileResponses', ['clinic'], unique=False)
    op.create_index(op.f('ix_ProfileResponses_profile'), 'ProfileResponses', ['profile'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ProfileResponses_profile'), table_name='ProfileResponses')
    op.drop_index(op.f('ix_ProfileResponses_clinic'), table_name='ProfileResponses')
    op.drop_table('ProfileResponses')
    op.drop_index(op.f('ix_OperationLog_clinic'), table_name='OperationLog')
    op.drop_table('OperationLog')
    op.drop_index(op.f('ix_OperationComp_clinic'), table_name='OperationComp')
    op.drop_table('OperationComp')
    op.drop_index(op.f('ix_IndicatorValues_history'), table_name='IndicatorValues')
    op.drop_index(op.f('ix_IndicatorValues_clinic'), table_name='IndicatorValues')
    op.drop_table('IndicatorValues')
    op.drop_index(op.f('ix_Operations_clinic'), table_name='Operations')
    op.drop_table('Operations')
    op.drop_index(op.f('ix_HistoryEvents_event'), table_name='HistoryEvents')
    op.drop_index(op.f('ix_HistoryEvents_doctor_researcher'), table_name='HistoryEvents')
    op.drop_index(op.f('ix_HistoryEvents_doctor_chief'), table_name='HistoryEvents')
    op.drop_index(op.f('ix_HistoryEvents_doctor'), table_name='HistoryEvents')
    op.drop_table('HistoryEvents')
    op.drop_index(op.f('ix_Diagnoses_history'), table_name='Diagnoses')
    op.drop_index(op.f('ix_Diagnoses_clinic'), table_name='Diagnoses')
    op.drop_table('Diagnoses')
    op.drop_index(op.f('ix_Histories_research_group'), table_name='Histories')
    op.drop_index(op.f('ix_Histories_clinic'), table_name='Histories')
    op.drop_table('Histories')
    # ### end Alembic commands ###
