"""test migrate

Revision ID: fabfd46593b0
Revises: 29a95f39cb12
Create Date: 2019-11-14 11:14:45.567274

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fabfd46593b0'
down_revision = '29a95f39cb12'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Users', sa.Column('email2', sa.String(length=100), nullable=True))
    op.create_index(op.f('ix_Users_email2'), 'Users', ['email2'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Users_email2'), table_name='Users')
    op.drop_column('Users', 'email2')
    # ### end Alembic commands ###
